name: Platform Linting and Tests (On Demand)

on:
  pull_request:
    types:
      - labeled

permissions: {}

concurrency:
  group: "platform-linting-and-tests-on-demand-${{ github.event.pull_request.number }}"
  cancel-in-progress: true

jobs:
  platform-linting-and-tests-on-demand:
    name: Platform Linting and Tests (On Demand)
    if: github.event.label.name == 'run-e2e'
    permissions:
      contents: write # Required for release-please codegen commits and checked-in report artifacts.
      security-events: write # Required for Docker Scout SARIF uploads.
      id-token: write # Required for Workload Identity Federation.
      pull-requests: write # Required for Docker Scout to write a comment to a PR.
    uses: ./.github/workflows/platform-linting-and-tests.yml
    with:
      should-skip-running-and-always-succeed: false
      is-fork-pr: ${{ github.event.pull_request.head.repo.fork == true }}
    secrets:
      TURBOREPO_REMOTE_CACHING_TOKEN: ${{ secrets.TURBOREPO_REMOTE_CACHING_TOKEN }}
      TURBOREPO_REMOTE_CACHING_TEAM: ${{ secrets.TURBOREPO_REMOTE_CACHING_TEAM }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GCP_SERVICE_ACCOUNT_NAME: ${{ secrets.DEVELOPMENT_OAUTH_PROXY_RELEASER_GCP_SERVICE_ACCOUNT_NAME }}
      GCP_WORKLOAD_IDENTITY_PROVIDER_IDENTIFIER: ${{ secrets.DEVELOPMENT_OAUTH_PROXY_RELEASER_GCP_WORKLOAD_IDENTITY_PROVIDER_IDENTIFIER }}
